---

build:armv7:
  image: shunyaos/shunya:armv7
  script:
    - opkg update
    - opkg install cmake libgpiod libgpiod-dev
    - cd assignments/practice/
    - mkdir build 
    - cd build
    - cmake ../
    - make 
